//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kodestruct.Dynamo.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kodestruct.Dynamo.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HSS20X.500
        ///HSS20X.375
        ///HSS18X.500
        ///HSS18X.375
        ///HSS16X.625
        ///HSS16X.500
        ///HSS16X.438
        ///HSS16X.375
        ///HSS16X.312
        ///HSS16X.250
        ///HSS14X.625
        ///HSS14X.500
        ///HSS14X.375
        ///HSS14X.312
        ///HSS14X.250
        ///HSS12.75X.500
        ///HSS12.75X.375
        ///HSS12.75X.250
        ///HSS10.75X.500
        ///HSS10.75X.375
        ///HSS10.75X.250
        ///HSS10X.625
        ///HSS10X.500
        ///HSS10X.375
        ///HSS10X.312
        ///HSS10X.250
        ///HSS10X.188
        ///HSS9.625X.500
        ///HSS9.625X.375
        ///HSS9.625X.312
        ///HSS9.625X.250
        ///HSS9.625X.188
        ///HSS8.625X.625
        ///HSS8.625X.500
        ///HSS8.625X.375
        ///HSS8.625X.322
        ///HSS8.625X.250
        ///HSS8.625X.188
        ///HSS7. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CHS_Shapes {
            get {
                return ResourceManager.GetString("CHS_Shapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C15X50
        ///C15X40
        ///C15X33.9
        ///C12X30
        ///C12X25
        ///C12X20.7
        ///C10X30
        ///C10X25
        ///C10X20
        ///C10X15.3
        ///C9X20
        ///C9X15
        ///C9X13.4
        ///C8X18.75
        ///C8X13.75
        ///C8X11.5
        ///C7X14.75
        ///C7X12.25
        ///C7X9.8
        ///C6X13
        ///C6X10.5
        ///C6X8.2
        ///C5X9
        ///C5X6.7
        ///C4X7.25
        ///C4X6.25
        ///C4X5.4
        ///C4X4.5
        ///C3X6
        ///C3X5
        ///C3X4.1
        ///C3X3.5
        ///.
        /// </summary>
        internal static string CShapes {
            get {
                return ResourceManager.GetString("CShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2L8X8X1-1/8
        ///2L8X8X1-1/8X3/8
        ///2L8X8X1-1/8X3/4
        ///2L8X8X1
        ///2L8X8X1X3/8
        ///2L8X8X1X3/4
        ///2L8X8X7/8
        ///2L8X8X7/8X3/8
        ///2L8X8X7/8X3/4
        ///2L8X8X3/4
        ///2L8X8X3/4X3/8
        ///2L8X8X3/4X3/4
        ///2L8X8X5/8
        ///2L8X8X5/8X3/8
        ///2L8X8X5/8X3/4
        ///2L8X8X9/16
        ///2L8X8X9/16X3/8
        ///2L8X8X9/16X3/4
        ///2L8X8X1/2
        ///2L8X8X1/2X3/8
        ///2L8X8X1/2X3/4
        ///2L6X6X1
        ///2L6X6X1X3/8
        ///2L6X6X1X3/4
        ///2L6X6X7/8
        ///2L6X6X7/8X3/8
        ///2L6X6X7/8X3/4
        ///2L6X6X3/4
        ///2L6X6X3/4X3/8
        ///2L6X6X3/4X3/4
        ///2L6X6X5/8
        ///2L6X6X5/8X3/8
        ///2L6X6X5/8X3/4
        ///2L6X6X9/16
        ///2L6X6X9/16X3/8
        ///2L6X6X9/16X3/4
        ///2L6X6X1/2
        ///2L6X6X1/2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string L2_Equal {
            get {
                return ResourceManager.GetString("L2_Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2L8X6X1LLBB
        ///2L8X6X1X3/8LLBB
        ///2L8X6X1X3/4LLBB
        ///2L8X6X7/8LLBB
        ///2L8X6X7/8X3/8LLBB
        ///2L8X6X7/8X3/4LLBB
        ///2L8X6X3/4LLBB
        ///2L8X6X3/4X3/8LLBB
        ///2L8X6X3/4X3/4LLBB
        ///2L8X6X5/8LLBB
        ///2L8X6X5/8X3/8LLBB
        ///2L8X6X5/8X3/4LLBB
        ///2L8X6X9/16LLBB
        ///2L8X6X9/16X3/8LLBB
        ///2L8X6X9/16X3/4LLBB
        ///2L8X6X1/2LLBB
        ///2L8X6X1/2X3/8LLBB
        ///2L8X6X1/2X3/4LLBB
        ///2L8X6X7/16LLBB
        ///2L8X6X7/16X3/8LLBB
        ///2L8X6X7/16X3/4LLBB
        ///2L8X4X1LLBB
        ///2L8X4X1X3/8LLBB
        ///2L8X4X1X3/4LLBB
        ///2L8X4X7/8LLBB
        ///2L8X4X7/8X3/8LLBB
        ///2L8X4X7/8X3/4LLBB
        ///2L8X4X3/4LLBB
        ///2L8X4X3/4X3/8LLBB
        ///2L8X4X3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string L2_LLBB {
            get {
                return ResourceManager.GetString("L2_LLBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2L8X6X1SLBB
        ///2L8X6X1X3/8SLBB
        ///2L8X6X1X3/4SLBB
        ///2L8X6X7/8SLBB
        ///2L8X6X7/8X3/8SLBB
        ///2L8X6X7/8X3/4SLBB
        ///2L8X6X3/4SLBB
        ///2L8X6X3/4X3/8SLBB
        ///2L8X6X3/4X3/4SLBB
        ///2L8X6X5/8SLBB
        ///2L8X6X5/8X3/8SLBB
        ///2L8X6X5/8X3/4SLBB
        ///2L8X6X9/16SLBB
        ///2L8X6X9/16X3/8SLBB
        ///2L8X6X9/16X3/4SLBB
        ///2L8X6X1/2SLBB
        ///2L8X6X1/2X3/8SLBB
        ///2L8X6X1/2X3/4SLBB
        ///2L8X6X7/16SLBB
        ///2L8X6X7/16X3/8SLBB
        ///2L8X6X7/16X3/4SLBB
        ///2L8X4X1SLBB
        ///2L8X4X1X3/8SLBB
        ///2L8X4X1X3/4SLBB
        ///2L8X4X7/8SLBB
        ///2L8X4X7/8X3/8SLBB
        ///2L8X4X7/8X3/4SLBB
        ///2L8X4X3/4SLBB
        ///2L8X4X3/4X3/8SLBB
        ///2L8X4X3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string L2_SLBB {
            get {
                return ResourceManager.GetString("L2_SLBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L8X8X1-1/8
        ///L8X8X1
        ///L8X8X7/8
        ///L8X8X3/4
        ///L8X8X5/8
        ///L8X8X9/16
        ///L8X8X1/2
        ///L8X6X1
        ///L8X6X7/8
        ///L8X6X3/4
        ///L8X6X5/8
        ///L8X6X9/16
        ///L8X6X1/2
        ///L8X6X7/16
        ///L8X4X1
        ///L8X4X7/8
        ///L8X4X3/4
        ///L8X4X5/8
        ///L8X4X9/16
        ///L8X4X1/2
        ///L8X4X7/16
        ///L7X4X3/4
        ///L7X4X5/8
        ///L7X4X1/2
        ///L7X4X7/16
        ///L7X4X3/8
        ///L6X6X1
        ///L6X6X7/8
        ///L6X6X3/4
        ///L6X6X5/8
        ///L6X6X9/16
        ///L6X6X1/2
        ///L6X6X7/16
        ///L6X6X3/8
        ///L6X6X5/16
        ///L6X4X7/8
        ///L6X4X3/4
        ///L6X4X5/8
        ///L6X4X9/16
        ///L6X4X1/2
        ///L6X4X7/16
        ///L6X4X3/8
        ///L6X4X5/16
        ///L6X3-1/2X1/2
        ///L6X3-1/2X3/8
        ///L6X3-1/2X5/16
        ///L5X5X7/8
        ///L5X5X3/4
        ///L5X5X5/8
        ///L5X [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LShapes {
            get {
                return ResourceManager.GetString("LShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MC18X58
        ///MC18X51.9
        ///MC18X45.8
        ///MC18X42.7
        ///MC13X50
        ///MC13X40
        ///MC13X35
        ///MC13X31.8
        ///MC12X50
        ///MC12X45
        ///MC12X40
        ///MC12X35
        ///MC12X31
        ///MC12X14.3
        ///MC12X10.6
        ///MC10X41.1
        ///MC10X33.6
        ///MC10X28.5
        ///MC10X25
        ///MC10X22
        ///MC10X8.4
        ///MC10X6.5
        ///MC9X25.4
        ///MC9X23.9
        ///MC8X22.8
        ///MC8X21.4
        ///MC8X20
        ///MC8X18.7
        ///MC8X8.5
        ///MC7X22.7
        ///MC7X19.1
        ///MC6X18
        ///MC6X15.3
        ///MC6X16.3
        ///MC6X15.1
        ///MC6X12
        ///MC6X7
        ///MC6X6.5
        ///MC4X13.8
        ///MC3X7.1
        ///.
        /// </summary>
        internal static string MCShapes {
            get {
                return ResourceManager.GetString("MCShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M12.5X12.4
        ///M12.5X11.6
        ///M12X11.8
        ///M12X10.8
        ///M12X10
        ///M10X9
        ///M10X8
        ///M10X7.5
        ///M8X6.5
        ///M8X6.2
        ///M6X4.4
        ///M6X3.7
        ///M5X18.9
        ///M4X6
        ///M4X4.08
        ///M4X3.45
        ///M4X3.2
        ///M3X2.9
        ///.
        /// </summary>
        internal static string MShapes {
            get {
                return ResourceManager.GetString("MShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT6.25X6.2
        ///MT6.25X5.8
        ///MT6X5.9
        ///MT6X5.4
        ///MT6X5
        ///MT5X4.5
        ///MT5X4
        ///MT5X3.75
        ///MT4X3.25
        ///MT4X3.1
        ///MT3X2.2
        ///MT3X1.85
        ///MT2.5X9.45
        ///MT2X3
        ///.
        /// </summary>
        internal static string MTShapes {
            get {
                return ResourceManager.GetString("MTShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipe12STD
        ///Pipe10SCH40
        ///Pipe8SCH40
        ///Pipe6SCH40
        ///Pipe5SCH40
        ///Pipe4SCH40
        ///Pipe3-1/2SCH40
        ///Pipe3SCH40
        ///Pipe2-1/2SCH40
        ///Pipe2SCH40
        ///Pipe1-1/2SCH40
        ///Pipe1-1/4SCH40
        ///Pipe1SCH40
        ///Pipe3/4SCH40
        ///Pipe1/2SCH40
        ///Pipe12XS
        ///Pipe10SCH80
        ///Pipe8SCH80
        ///Pipe6SCH80
        ///Pipe5SCH80
        ///Pipe4SCH80
        ///Pipe3-1/2SCH80
        ///Pipe3SCH80
        ///Pipe2-1/2SCH80
        ///Pipe2SCH80
        ///Pipe1-1/2SCH80
        ///Pipe1-1/4SCH80
        ///Pipe1SCH80
        ///Pipe3/4SCH80
        ///Pipe1/2SCH80
        ///Pipe8XXS
        ///Pipe6XXS
        ///Pipe5XXS
        ///Pipe4XXS
        ///Pipe3XXS
        ///Pipe2-1/2XXS
        ///Pipe2XXS
        ///.
        /// </summary>
        internal static string PipeShapes {
            get {
                return ResourceManager.GetString("PipeShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HSS20X12X.625
        ///HSS20X12X.500
        ///HSS20X12X.375
        ///HSS20X12X.313
        ///HSS20X8X.625
        ///HSS20X8X.500
        ///HSS20X8X.375
        ///HSS20X8X.313
        ///HSS20X4X.500
        ///HSS20X4X.375
        ///HSS20X4X.313
        ///HSS20X4X.250
        ///HSS18X6X.625
        ///HSS18X6X.500
        ///HSS18X6X.375
        ///HSS18X6X.313
        ///HSS18X6X.250
        ///HSS16X16X.625
        ///HSS16X16X.500
        ///HSS16X16X.375
        ///HSS16X16X.313
        ///HSS16X12X.625
        ///HSS16X12X.500
        ///HSS16X12X.375
        ///HSS16X12X.313
        ///HSS16X8X.625
        ///HSS16X8X.500
        ///HSS16X8X.375
        ///HSS16X8X.313
        ///HSS16X8X.250
        ///HSS16X4X.625
        ///HSS16X4X.500
        ///HSS16X4X.375
        ///HSS16X4X.313
        ///HSS16X4X.250
        ///HSS16X4X.1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RHS_Shapes {
            get {
                return ResourceManager.GetString("RHS_Shapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IShape,A,d,bf,tw,tf,Ix,Zx,Sx,rx,Iy2,Zy,Sy,ry,J,Cw
        ///Channel,A,d,bf,tw,tf,x,eo,xp,Ix,Zx,Sx,rx,Iy3,Zy,Sy,ry,J,Cw
        ///Angle,A,d,B,x,y,xp,yp,Ix,Zx,Sx,rx,Iy4,Zy,Sy,ry,Iz,Sz,rz,J,Cw
        ///Tee,A,d,bf,tw,tf,y,yp,Ix,Zx,Sx,rx,Iy5,Zy,Sy,ry,J,Cw
        ///DoubleAngle,A,d,B,y,yp,Ix,Zx,Sx,rx,Iy6,Zy,Sy,ry
        ///CircularHSS,A,D,tnom,t,Ix,Zx,Sx,rx,Iy7,Zy,Sy,ry,J
        ///RectangularHSS,A,Ht,B,tnom,t,Ix,Zx,Sx,rx,Iy8,Zy,Sy,ry,J.
        /// </summary>
        internal static string SectionSpecificProperties {
            get {
                return ResourceManager.GetString("SectionSpecificProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S24X121
        ///S24X106
        ///S24X100
        ///S24X90
        ///S24X80
        ///S20X96
        ///S20X86
        ///S20X75
        ///S20X66
        ///S18X70
        ///S18X54.7
        ///S15X50
        ///S15X42.9
        ///S12X50
        ///S12X40.8
        ///S12X35
        ///S12X31.8
        ///S10X35
        ///S10X25.4
        ///S8X23
        ///S8X18.4
        ///S6X17.25
        ///S6X12.5
        ///S5X10
        ///S4X9.5
        ///S4X7.7
        ///S3X7.5
        ///S3X5.7.
        /// </summary>
        internal static string SShapes {
            get {
                return ResourceManager.GetString("SShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ST12X60.5
        ///ST12X53
        ///ST12X50
        ///ST12X45
        ///ST12X40
        ///ST10X48
        ///ST10X43
        ///ST10X37.5
        ///ST10X33
        ///ST9X35
        ///ST9X27.35
        ///ST7.5X25
        ///ST7.5X21.45
        ///ST6X25
        ///ST6X20.4
        ///ST6X17.5
        ///ST6X15.9
        ///ST5X17.5
        ///ST5X12.7
        ///ST4X11.5
        ///ST4X9.2
        ///ST3X8.6
        ///ST3X6.25
        ///ST2.5X5
        ///ST2X4.75
        ///ST2X3.85
        ///ST1.5X3.75
        ///ST1.5X2.85
        ///.
        /// </summary>
        internal static string STShapes {
            get {
                return ResourceManager.GetString("STShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W44X335
        ///W44X290
        ///W44X262
        ///W44X230
        ///W40X593
        ///W40X503
        ///W40X431
        ///W40X397
        ///W40X372
        ///W40X362
        ///W40X324
        ///W40X297
        ///W40X277
        ///W40X249
        ///W40X215
        ///W40X199
        ///W40X392
        ///W40X331
        ///W40X327
        ///W40X294
        ///W40X278
        ///W40X264
        ///W40X235
        ///W40X211
        ///W40X183
        ///W40X167
        ///W40X149
        ///W36X652
        ///W36X529
        ///W36X487
        ///W36X441
        ///W36X395
        ///W36X361
        ///W36X330
        ///W36X302
        ///W36X282
        ///W36X262
        ///W36X247
        ///W36X231
        ///W36X256
        ///W36X232
        ///W36X210
        ///W36X194
        ///W36X182
        ///W36X170
        ///W36X160
        ///W36X150
        ///W36X135
        ///W33X387
        ///W33X354
        ///W33X318
        ///W33X291
        ///W33X263
        ///W33X241
        ///W33X221
        ///W33X201
        ///W33X169
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WShapes {
            get {
                return ResourceManager.GetString("WShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WT22X167.5
        ///WT22X145
        ///WT22X131
        ///WT22X115
        ///WT20X296.5
        ///WT20X251.5
        ///WT20X215.5
        ///WT20X198.5
        ///WT20X186
        ///WT20X181
        ///WT20X162
        ///WT20X148.5
        ///WT20X138.5
        ///WT20X124.5
        ///WT20X107.5
        ///WT20X99.5
        ///WT20X196
        ///WT20X165.5
        ///WT20X163.5
        ///WT20X147
        ///WT20X139
        ///WT20X132
        ///WT20X117.5
        ///WT20X105.5
        ///WT20X91.5
        ///WT20X83.5
        ///WT20X74.5
        ///WT18X326
        ///WT18X264.5
        ///WT18X243.5
        ///WT18X220.5
        ///WT18X197.5
        ///WT18X180.5
        ///WT18X165
        ///WT18X151
        ///WT18X141
        ///WT18X131
        ///WT18X123.5
        ///WT18X115.5
        ///WT18X128
        ///WT18X116
        ///WT18X105
        ///WT18X97
        ///WT18X91
        ///WT18X85
        ///WT18X80
        ///WT18X75
        ///WT1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WTShapes {
            get {
                return ResourceManager.GetString("WTShapes", resourceCulture);
            }
        }
    }
}
